apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: growoduck
  labels:
    app: frontend
spec:
  replicas: 5 # HPA will handle scaling
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: maccotech/macstrom-website:v1.11
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "300m" # Minimum guaranteed CPU
            memory: "512Mi" # Minimum guaranteed RAM
          limits:
            cpu: "1000m" # Max CPU per pod
            memory: "2Gi" # Max RAM per pod
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: growoduck
spec:
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP


---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: growoduck
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-deployment
  minReplicas: 5
  maxReplicas: 200
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30 # Reduce delay in scaling up
      policies:
      - type: Percent
        value: 50
        periodSeconds: 15 # Allow 50% increase every 15s
    scaleDown:
      stabilizationWindowSeconds: 60 # Prevent rapid scale down
      policies:
      - type: Percent
        value: 20
        periodSeconds: 30 # Allow 20% decrease every 30s
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: growoduck

  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

spec:
  ingressClassName: alb

  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix

        backend:
          service:
            name: frontend-service
            port:
              number: 3000

