apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetry-deployment
  namespace: growdeck
spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend-opentelemetry

  template:
    metadata:
      labels:
        app: backend-opentelemetry

    spec:
      containers:
        - name: backend
          image: affiefly/offerwall-backend-prod:v0.101
          imagePullPolicy: Always
          command: ["node"]
          args: ["--import", "./instrumentation.mjs", "app.js"]
          envFrom:
            - secretRef:
                name: backend-offerwall-secret

          env:
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"

          ports:
            - containerPort: 5000

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"


---
apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-service
  namespace: growdeck
  labels:
    app: backend-opentelemetry
spec:
  selector:
    app: backend-opentelemetry
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  type: ClusterIP

