# apiVersion: batch/v1
# kind: CronJob
# metadata:
#   name: backend-cron
#   namespace: growdeck
# spec:
#   schedule: "*/5 * * * *"
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           containers:
#           - name: backend-cron
#             image: affiefly/offerwall-backend-prod:v0.48
#             command: ["node"]
#             args: ["nodeCron.js"]
#           restartPolicy: OnFailure


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-backend-cron-deployment
  namespace: growdeck
  labels:
    app: analytics-backend-cron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-backend-cron
  template:
    metadata:
      labels:
        app: analytics-backend-cron
    spec:
      containers:
      - name: analytics-backend-corn
        image: affiefly/analytics-backend-prod:v0.9
        imagePullPolicy: Always
        command: ["node"]
        args: ["cronJob.js"]
        envFrom:
          - secretRef:
              name: backend-analytics-secret
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "2Gi"
            cpu: "3000m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-backend-worker-deployment
  namespace: growdeck
  labels:
    app: analytics-backend-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-backend-worker
  template:
    metadata:
      labels:
        app: analytics-backend-worker
    spec:
      containers:
      - name: analytics-backend-worker
        image: affiefly/analytics-backend-prod:v0.9
        imagePullPolicy: Always
        command: ["node"]
        args: ["bullMQ.js"]
        envFrom:
          - secretRef:
              name: backend-analytics-secret
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "2Gi"
            cpu: "3000m"