# apiVersion: external-secrets.io/v1
# kind: ClusterSecretStore
# metadata:
#   name: aws-secret-store
# spec:
#   provider:
#     aws:
#       service: SecretsManager
#       region: ap-south-1
#       auth:
#         jwt:
#           serviceAccountRef:
#             name: external-secrets
#             namespace: external-secrets

# ---
# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: backend-offerwall-secret
#   namespace: growdeck
# spec:
#   refreshInterval: 1h

#   secretStoreRef:
#     name: aws-secret-store
#     kind: ClusterSecretStore

#   target:
#     name: backend-offerwall-secret

#   dataFrom:
#     - extract:
#         key: growdeck/backend-offerwall